name: Build and deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0-alpha - 3.11.20

      - name: Build
        run: python timeline.py timeline.toml

      - name: Upload
        uses: actions/upload-pages-artifact@v0.1.0
        with:
          path: site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
